// Shared greeting pose: dimensional artwork, persona accessories, calm continuous idle.
const canvas=document.createElement('canvas');canvas.className='cast-canvas';canvas.setAttribute('role','img');canvas.setAttribute('aria-label','Six welcoming OpenGym companions with their persona accessories');
const ctx=canvas.getContext('2d'),sheet=new Image();sheet.src='./cast-editorial.png';
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
let host=null,mode='login',selected=0,camera=2.5,pointer=0,lastBounds=null,revealMix=1;
function attach(){const next=document.querySelector('.cast-stage');if(!next)return;selected=Number(next.dataset.character||0);mode=next.dataset.mode||'login';if(host!==next){const old=host?.isConnected?host.getBoundingClientRect():lastBounds;host=next;host.append(canvas);const r=host.getBoundingClientRect();if(old?.width&&!reduced()&&host.dataset.reveal!=='1')canvas.animate([{transform:`translate(${old.left-r.left}px,${old.top-r.top}px) scale(${old.width/r.width},${old.height/r.height})`},{transform:'none'}],{duration:850,easing:'cubic-bezier(.16,1,.3,1)'});lastBounds=r;if(host.dataset.reveal==='1')revealMix=0;host.onpointermove=e=>{const r=host.getBoundingClientRect();pointer=(e.clientX-r.left)/r.width-.5;};host.onpointerleave=()=>pointer=0;}}
new MutationObserver(attach).observe(document.querySelector('#app'),{childList:true,subtree:true,attributes:true,attributeFilter:['data-character']});
const cuts=[0,1,2,3,4,5,6];
function drawCharacter(i,x,bottom,height,now,opacity=1){if(!sheet.complete||!sheet.naturalWidth)return;const k=sheet.naturalWidth/6,sx=cuts[i]*k,sw=k,sh=sheet.naturalHeight*(mode==='dashboard'?.59:1),width=height*sw/sh;const idle=reduced()?0:Math.sin(now/1600+i*.2);ctx.save();ctx.globalAlpha=opacity;if(mode!=='dashboard'){ctx.fillStyle='rgba(92,65,47,.07)';ctx.beginPath();ctx.ellipse(x,bottom-2,width*.25,3,0,0,Math.PI*2);ctx.fill();}ctx.translate(x,bottom);ctx.rotate(idle*.004);ctx.scale(1,1+idle*.002);ctx.drawImage(sheet,sx,0,sw,sh,-width/2,-height,width,height);ctx.restore();}
let previous=0;
function frame(now){attach();if(host?.isConnected){const r=host.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';const dt=Math.min(50,now-previous||16),ease=reduced()?1:1-Math.exp(-dt/180);camera+=(selected-camera)*ease;revealMix+=((host.dataset.reveal==='1'?0:1)-revealMix)*ease;
if(mode==='dashboard')drawCharacter(selected,r.width/2+pointer*3,r.height-12,r.height-18,now);
else if(mode==='selection'){const gap=Math.max(105,r.width/6.7);for(let i=0;i<6;i++){const focus=Math.max(0,1-Math.abs(i-camera)),lineX=(i+.5)*r.width/6,focusX=r.width/2+(i-camera)*gap;drawCharacter(i,lineX+(focusX-lineX)*revealMix+pointer*3,r.height-10,(r.height-20)*(.7+.3*focus*revealMix),now,1-(1-focus)*.18*revealMix);}}
else for(let i=0;i<6;i++)drawCharacter(i,(i+.5)*r.width/6,r.height-10,r.height*.82,now);
}previous=now;requestAnimationFrame(frame);}requestAnimationFrame(frame);
